// Headless test runner for the arena logic (no browser/DB needed).
//   node test/run.js
const { execFileSync } = require('child_process');
const path = require('path');
const tests = ['test-pause.js', 'test-ui-dialog.js', 'test-v3.js', 'test-scoring.js', 'test-rules.js', 'test-mobs.js', 'test-gamepad-nav.js', 'test-weapons.js', 'test-foliage.js', 'test-detection.js', 'test-webs.js', 'test-pathfinding.js', 'test-wayfinding.js', 'test-platformer-defaults.js', 'test-bot-ai.js', 'test-bot-climb.js', 'test-redstone.js', 'test-keybindings.js', 'test-boomerang.js', 'test-grapple.js', 'test-travel-tube.js', 'test-moving-platform.js', 'test-speed-booster.js', 'test-wind-zone.js', 'test-achievement-eval.js', 'test-beat-grid.js', 'test-bpm-detect.js', 'test-spike-orient.js', 'test-palette-filter.js', 'test-speedrun-stats.js', 'test-sr-presets.js', 'test-moderation.js', 'test-level-validator.js', 'test-directional.js', 'test-combos.js', 'test-testworld.js', 'test-gpbindings.js', 'test-weight-sensor.js', 'test-conduct.js', 'test-block-skins.js', 'test-rail-switch.js', 'test-campaign.js', 'test-jump-attack.js', 'test-overhead-core.js', 'test-overhead-map.js', 'test-overhead-play.js', 'test-overhead-play-path.js', 'test-player-looks.js', 'test-characters.js', 'test-character-persist.js', 'test-phase3-multichar.js', 'test-persist-world-data.js', 'test-character-builder.js', 'test-overhead-sprite-accessories.js', 'test-overhead-character.js', 'test-overhead-modes.js', 'test-overhead-weapons.js', 'test-overhead-daynight.js', 'test-overhead-redstone.js', 'test-overhead-qa-world.js', 'test-overhead-keys.js', 'test-overhead-glass.js', 'test-overhead-tube.js', 'test-overhead-speedrun.js', 'test-glass-block.js', 'test-overhead-templates.js', 'test-overhead-climb.js', 'test-overhead-pistons.js', 'test-overhead-gates.js', 'test-overhead-fixes.js', 'test-overhead-editor-perf.js', 'test-overhead-editor-elev.js', 'test-world-transfer.js', 'test-world-transfer-qa347.js', 'test-sandbox-confirm.js', 'test-overhead-settings-schema.js', 'test-overhead-bake.js', 'test-overhead-occlusion.js', 'test-arena-classic-blocks.js', 'test-designer-locks.js', 'test-qa-fixes-347.js', 'test-overhead-rails.js', 'test-overhead-perf.js', 'test-audio-perf.js', 'test-aim-style.js', 'test-export-hidden.js', 'test-overhead-editor-selmove.js', 'test-overhead-multiplayer.js'];
let failed = 0;
for (const t of tests) {
  process.stdout.write(`\n=== ${t} ===\n`);
  try { process.stdout.write(execFileSync('node', [path.join(__dirname, t)], { encoding: 'utf8' })); }
  catch (e) { failed++; process.stdout.write((e.stdout || '') + (e.stderr || '')); }
}
process.stdout.write(failed ? `\n${failed} test file(s) FAILED\n` : `\nAll test files passed\n`);
process.exit(failed ? 1 : 0);
